crm/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/lead/urls.py
from django.urls import path
from .views import *

app_name = 'lead'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead_list'),
    path('add_lead/', add_lead, name='add_lead'),
    path('<int:pk>/', lead_detail, name='lead_detail'),
    path('<int:pk>/delete/', leads_delete, name='lead_delete'),
    path('<int:pk>/edit/', leads_edit, name='leads_edit'),
    path('<int:pk>/convert/', convert_to_client, name='convert_to_client'),
    path('<int:pk>/add-comment', add_comment, name='add_comment'),
]

crm/user/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import signup, my_account

app_name = 'user'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('myaccount/', my_account, name='my_account'),
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

crm/lead/models.py
from django.db import models

from django.contrib.auth.models import User
from client.models import Client

from team.models import Team

class Lead(models.Model):
    LOW  = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW,'Low'),
        (MEDIUM,'Medium'),
        (HIGH,'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW,'New'),
        (CONTACTED,'Contacted'),
        (WON, 'Won'),
        (LOST,'Lost'),
    )

    team = models.ForeignKey(Team,related_name='leads', on_delete=models.CASCADE)
    name  = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY,default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    

    def __str__(self) -> str:
        return self.name
    

class LeadFile(models.Model):
    team = models.ForeignKey(Team,related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead,related_name='files', on_delete=models.CASCADE)

    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.created_by.username
   


    

class Comment(models.Model):
    team = models.ForeignKey(Team,related_name='lead_comment', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead,related_name='comments', on_delete=models.CASCADE)

    content = models.TextField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.created_by.username
   
    

    

crm/lead/forms.py
from django import forms

from .models import Lead, Comment, LeadFile

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name','email', 'description', 'priority', 'status',)

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)
    

crm/lead/views.py
from django.views import View
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .forms import AddLeadForm, AddCommentForm, AddFileForm
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from .models import Comment, Lead
from client.models import Client, Comment as clientcomment
from team.models import Team
from django.views.generic import ListView, DetailView, DeleteView
from django.utils.decorators import method_decorator





class LeadListView(LoginRequiredMixin, ListView):
    model = Lead
    template_name = 'lead/lead_list.html'
    context_object_name = 'leads'
    paginate_by = 10
    
    def get_queryset(self):
        return self.model.objects.filter(created_by=self.request.user, converted_to_client=False)


    
@login_required
def lead_detail(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    comments = Comment.objects.filter(lead=lead)
    form1 = AddFileForm()
    form2 = AddCommentForm()
    context = {
        'lead': lead,
        'comments': comments,
        'form1':form1,
        'form2':form2
    }
    return render(request, 'lead/lead_detail.html', context)


@login_required
def leads_delete(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead.delete()
    messages.success(request, 'The lead deleted successfully!')
    return redirect('lead:lead_list')


@login_required
def leads_edit(request,pk):
    print('leads_edit view called') 
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    if request.method == 'POST':
        print('POST request received')
        form = AddLeadForm(request.POST, instance=lead)

        if form.is_valid():
            form.save()
        
        messages.success(request, 'Lead updated successfully!')

        return redirect('lead:lead_list')
    
    else:
        print('GET request received')
        form=AddLeadForm(instance=lead)
    
    return render(request, 'lead/leads_edit.html',{
        "form":form
    })
@login_required
def add_lead(request):
    teams = Team.objects.filter(created_by=request.user)
    if teams.exists():
        team = teams.first()
    else:
        team = None
    if request.method == 'POST':
        form = AddLeadForm(request.POST)
        if form.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user
            lead.team = team
            lead.save()

            messages.success(request, 'The lead added successfully!')

            return redirect('lead:lead_list')
    else:
        form_initial = {}
        if team:
            form_initial['team'] = team.id
        form = AddLeadForm(initial=form_initial)

    return render(request, 'lead/add_lead.html',{
        "form":form,
        "team":team
    })



@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    teams = Team.objects.filter(created_by=request.user)
    if teams.exists():
        team = teams.first()
    else:
        team = None

    client = Client.objects.create(
        name=lead.name,
        email=lead.email,
        description=lead.description,
        created_by=request.user,
        team=team,
    )

    lead.converted_to_client=True
    lead.save()

    # convert lead comments to clients comments
    comments = lead.comments.all()
    
    for comment in comments:
        clientcomment.objects.create(
            client = client,
            content = comment.content,
            created_by = comment.created_by,
            team = team

        )
    
    # show message and redirect

    messages.success(request, 'The lead converted to a client successfully!')
    return redirect('lead:lead_list')


@login_required
def add_comment(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    teams = Team.objects.filter(created_by=request.user)
    if teams.exists():
        team = teams.first()
    else:
        team = None
    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_by = request.user
            comment.team = team
            comment.lead = lead
            comment.save()

            messages.success(request, 'The comment added successfully!')

            return redirect('lead:lead_detail', pk=pk)
    else:
        form_initial = {}
        if team:
            form_initial['team'] = team.id
        form = AddCommentForm(initial=form_initial)

    return render(request, 'lead/add_comment.html', {
        "form": form,
        "team": team,
    })

crm/lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}

{% block title %}Lead | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-6 bg-gray-100">
        <h1 class="text-2xl font-bold mb-4">Add Lead</h1>
        
        {% if team.plan.max_leads|length >= team.leads.all|length %}
            Num leads: {{ team.leads.all|length }}

            <form method="post" action="." class="max-w-lg mx-auto bg-white rounded-lg shadow-lg p-6">
                {% csrf_token %}

                <div class="mb-4">
                    <label for="name" class="block text-gray-700 font-bold mb-2">Name</label>
                    {{ form.name }}
                </div>

                <div class="mb-4">
                    <label for="email" class="block text-gray-700 font-bold mb-2">Email</label>
                    {{ form.email }}
                </div>

                <div class="mb-4">
                    <label for="phone" class="block text-gray-700 font-bold mb-2">Description</label>
                    {{ form.description }}
                </div>

                <div class="mb-4">
                    <label for="message" class="block text-gray-700 font-bold mb-2">Priority</label>
                    {{ form.priority }}
                </div>
                <div class="mb-4">
                    <label for="message" class="block text-gray-700 font-bold mb-2">Status</label>
                    {{ form.status }}
                </div>

                <div class="flex justify-center">
                    <button class="bg-teal-500 hover:bg-teal-600 text-white font-bold py-2 px-4 rounded">
                        Submit
                    </button>
                </div>
            </form>
        {% else %}
            <p>Oops! You have reached your limit.</p>
        {% endif %}
    </div>
{% endblock %}

crm/lead/templates/lead/lead_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}Delete | {{ block.super }}{% endblock %}

{% block content %}
    <h1 class="mb-6 mt-6 text-xs">You have successfully deleted the lead</h1>
    <a href="{% url 'lead:get_the_leads' %}" class="inline-flex items-center text-blue-600 hover:text-blue-800 hover:border-blue-600 hover:bg-blue-100 border rounded-md px-3 py-2 transition duration-300 ease-in-out">
        <svg class="mr-2" xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>
        Go to leads...
    </a>

    
    
{% endblock %}

crm/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }} | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-2xl font-bold">{{ lead.name }}</h1>

        {% if lead.description %}
            <p class="font-semibold text-gray-600 mb-2">Description:</p>
            <p class="mb-6">{{ lead.description }}</p>
        {% endif %}

        <div class="flex flex-col md:flex-row">
            <div class="md:w-1/3">
                <p class="font-semibold text-gray-600 mb-2">Priority:</p>
                <p class="mb-6">{{ lead.get_priority_display }}</p>
            </div>
            <div class="md:w-1/3">
                <p class="font-semibold text-gray-600 mb-2">Status:</p>
                <p class="mb-6">{{ lead.get_status_display }}</p>
            </div>
            <div class="md:w-1/3">
                <p class="font-semibold text-gray-600 mb-2">Created by:</p>
                <p class="mb-6">{{ lead.created_by }}</p>
            </div>
        </div>

        <div class="flex flex-col md:flex-row">
            <div class="md:w-1/2">
                <p class="font-semibold text-gray-600 mb-2">Created at:</p>
                <p class="mb-6">{{ lead.created_at|date:"d-M-Y H:i" }}</p>
            </div>
            <div class="md:w-1/2">
                <p class="font-semibold text-gray-600 mb-2">Modified at:</p>
                <p class="mb-6">{{ lead.modified_at|date:"d-M-Y H:i" }}</p>
            </div>
        </div>
        <hr class="my-4">
        <a class="py-2 px-6 bg-red-800  hover:underline hover:text-white rounded-xl" href="{% url 'lead:lead_delete' lead.pk %}">Delete</a>
        <a class="py-2 px-6 bg-teal-800  hover:underline hover:text-white rounded-xl" href="{% url 'lead:leads_edit' lead.pk %}">Edit</a>
        <a class="py-2 px-6 bg-blue-800  hover:underline hover:text-white rounded-xl" href="{% url 'lead:convert_to_client' lead.pk %}">Convert to client</a>
        <hr class="my-4">
        <div class="bg-gray-100 rounded-lg shadow-lg p-6">
            <h2 class="text-lg font-semibold mb-4">Comments</h2>
            {% for comment in lead.comments.all %}
                <div class="bg-white rounded-lg shadow-md p-4 mb-4">
                    <div class="flex items-center mb-2">
                    <img src="{{ comment.created_by.profile.image.url }}" alt="{{ comment.created_by.username }}" class="w-8 h-8 rounded-full mr-2">
                    <p class="text-sm font-medium">{{ comment.created_by.username }}</p>
                    <p class="text-gray-500 text-xs ml-auto">{{ comment.created_at|date:"M d, Y" }}</p>
                    </div>
                    <p class="text-gray-700">{{ comment.content }}</p>
                    {% if comment.created_by == request.user %}
                        <div class="mt-2 flex justify-end">
                            <a href="#" class="text-blue-500 hover:underline mr-2">Edit</a>
                            <form action="#" method="post">
                            {% csrf_token %}
                            <button type="submit" class="text-red-500 hover:underline">Delete</button>
                            </form>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            {% if user.is_authenticated %}
              <form action="{% url 'lead:add_comment' lead.id %}" method="post">
                {% csrf_token %}
                <textarea name="content" class="bg-gray-200 rounded-lg w-full p-2 mb-2" rows="3" placeholder="Add a comment..."></textarea>
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">Post Comment</button>
              </form>
            {% else %}
              <p class="text-sm mt-4"><a href="{% url 'user:login' %}" class="text-blue-500 hover:underline">Log in</a> to leave a comment.</p>
            {% endif %}
            <hr class="mt-4">
            <h2 class="text-lg">Files</h2>
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
        
                    {{ fileform.as_p }}
        
                    <button class="py-2 px-6  bg-teal-500 hover:underline hover:text-white rounded-xl">Submit</button>
                </form>
            </div>
          

    {% endblock %}

crm/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Leads | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <h1 class="text-3xl font-bold mb-4">Leads</h1>
        <a href="{% url 'lead:add_lead' %}" class="inline-block py-3 px-6 bg-teal-600 rounded-lg text-white hover:bg-teal-700 transition-colors duration-200">Add lead</a>
        {% if leads %}
            <div class="mt-6 grid grid-cols-3 gap-4 bg-gray-500 rounded-t-lg text-white font-semibold">
                <div class="py-4 px-6">Name</div>
                <div class="py-4 px-6">Priority</div>
                <div class="py-4 px-6">Status</div>
            </div>
            <p class="text-sm">Total leads: {{ team.leads.all|length }}</p>
            {% for lead in leads %}
                <div class="flex flex-col sm:flex-row justify-between items-center py-4 border-b border-gray-300">
                    <div class="flex items-center justify-between sm:w-3/5 md:w-2/5 py-2 sm:border-r sm:pr-6">
                        <div class="font-semibold text-gray-800">
                            <a href="{% url 'lead:lead_detail' lead.id %}" class="hover:underline">{{ lead.name }}</a>
                        </div>
                        <div class="text-gray-500 text-sm ml-2">{{ lead.created_on|date:'F j, Y' }}</div>
                    </div>
                    <div class="w-full sm:w-1/5 md:w-2/5 py-2 sm:border-r sm:px-6">{{ lead.get_priority_display }}</div>
                    <div class="w-full sm:w-1/5 md:w-1/5 py-2 sm:px-6">{{ lead.get_status_display }}</div>
                </div>
            {% endfor %}
        {% else %}
                <P class="mt-6 px-4">There are no leads yet...</P>
        {% endif%}
    </div>
{% endblock %}

crm/lead/templates/lead/leads_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit-lead | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-6 bg-gray-100">
        <h1 class="text-2xl font-bold mb-4">Edit Lead</h1>

        <form method="post" action="." class="max-w-lg mx-auto bg-white rounded-lg shadow-lg p-6">
            {% csrf_token %}

            <div class="mb-4">
                <label for="name" class="block text-gray-700 font-bold mb-2">Name</label>
                {{ form.name }}
            </div>

            <div class="mb-4">
                <label for="email" class="block text-gray-700 font-bold mb-2">Email</label>
                {{ form.email }}
            </div>

            <div class="mb-4">
                <label for="phone" class="block text-gray-700 font-bold mb-2">Description</label>
                {{ form.description }}
            </div>

            <div class="mb-4">
                <label for="message" class="block text-gray-700 font-bold mb-2">Priority</label>
                {{ form.priority }}
            </div>
            <div class="mb-4">
                <label for="message" class="block text-gray-700 font-bold mb-2">Status</label>
                {{ form.status }}
            </div>

            <div class="flex justify-center">
                <button class="bg-teal-500 hover:bg-teal-600 text-white font-bold py-2 px-4 rounded">
                    Submit
                </button>
            </div>
        </form>
    </div>
{% endblock %}