crm/client/urls.py
from django.urls import path

from .views import *

app_name = 'client'

urlpatterns = [
    path('', client_list, name='client_list'),
    path('<int:pk>/', client_detail, name='client_detail'),
    path('<int:pk>/delete/', client_delete, name='client_delete'),
    path('<int:pk>/comment-delete/', delete_comment, name='comment_delete'),
    path('<int:pk>/edit/', client_edit, name='client_edit'),
    path('<int:pk>/add-comment/', client_detail, name='add_comment'),
    path('add/', add_client, name='add_client'),
    path('export/',client_export,name='client_export'),
    
    
]

crm/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/dashboard/urls.py
from django.urls import path

from .views import dashboard

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard , name='dashboard'),
]

crm/lead/urls.py
from django.urls import path
from .views import *

app_name = 'lead'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead_list'),
    path('add_lead/', add_lead, name='add_lead'),
    path('<int:pk>/', lead_detail, name='lead_detail'),
    path('<int:pk>/delete/', leads_delete, name='lead_delete'),
    path('<int:pk>/edit/', leads_edit, name='leads_edit'),
    path('<int:pk>/convert/', convert_to_client, name='convert_to_client'),
    path('<int:pk>/add-comment', add_comment, name='add_comment'),
]

crm/dashboard/models.py
from django.db import models

crm/lead/models.py
from django.db import models

from django.contrib.auth.models import User
from client.models import Client

from team.models import Team

class Lead(models.Model):
    LOW  = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW,'Low'),
        (MEDIUM,'Medium'),
        (HIGH,'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW,'New'),
        (CONTACTED,'Contacted'),
        (WON, 'Won'),
        (LOST,'Lost'),
    )

    team = models.ForeignKey(Team,related_name='leads', on_delete=models.CASCADE)
    name  = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY,default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    

    def __str__(self) -> str:
        return self.name
    

class LeadFile(models.Model):
    team = models.ForeignKey(Team,related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead,related_name='files', on_delete=models.CASCADE)

    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.created_by.username
   


    

class Comment(models.Model):
    team = models.ForeignKey(Team,related_name='lead_comment', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead,related_name='comments', on_delete=models.CASCADE)

    content = models.TextField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.created_by.username
   
    

    

crm/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from lead.models import Lead
from client.models import Client
from team.models import Team

@login_required
def dashboard(request):
    team = Team.objects.filter(created_by=request.user)
    if team.exists():
        team = team.first()
    else:
        team = None
    leads = Lead.objects.filter( created_by=request.user,team=team, converted_to_client=False).order_by('-created_at')[0:5]
    clients = Client.objects.filter(created_by=request.user,team=team).order_by('-created_at')[0:5]
    return render(request,'dashboard/dashboard.html',{
        'leads':leads,
        'clients':clients,
        'team':team
    })

crm/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}

{% block content %}
    <div class="bg-gray-100 py-6 px-6">
        <div class="py-6 px-6">
            <h1 class="mb-6 text-2xl font-bold text-gray-900">Dashboard</h1>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="p-6 bg-white rounded-xl shadow-lg">
                    <h3 class="mb-4 text-lg font-bold text-gray-900 text-center">Newest leads</h3>
                    {% for lead in leads %}
                        <div class="mb-4 border-b border-gray-200 pb-4">
                            <h3 class="text-xl font-semibold">{{ lead.name }}</h3>
                            <p class="text-sm text-gray-500">Status: {{ lead.get_status_display }}</p>
                            <p class="text-sm text-gray-500">Priority: {{ lead.get_priority_display }}</p>
                            <a href="{% url 'lead:lead_detail' lead.id %}" class="text-sm text-teal-500 hover:text-teal-700">Details</a>
                        </div>
                    {% endfor %}
                </div>
                <div class="p-6 bg-white rounded-xl shadow-lg">
                    <h3 class="mb-4 text-lg font-bold text-gray-900 text-center">Newest clients</h3>
                    {% for client in clients %}
                        <div class="mb-4 border-b border-gray-200 pb-4">
                            <h3 class="text-xl font-semibold">{{ client.name }}</h3>
                            <a href="{% url 'client:client_detail' client.pk %}" class="text-sm text-teal-500 hover:text-teal-700">Details</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}