crm/client/urls.py
from django.urls import path

from .views import *

app_name = 'client'

urlpatterns = [
    path('', client_list, name='client_list'),
    path('<int:pk>/', client_detail, name='client_detail'),
    path('<int:pk>/delete/', client_delete, name='client_delete'),
    path('<int:pk>/comment-delete/', delete_comment, name='comment_delete'),
    path('<int:pk>/edit/', client_edit, name='client_edit'),
    path('<int:pk>/add-comment/', client_detail, name='add_comment'),
    path('add/', add_client, name='add_client'),
    path('export/',client_export,name='client_export'),
    
    
]

crm/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import index, about

app_name = 'core'

urlpatterns = [
    path('', login_required(index) , name='index'),
    path('about/', about , name='about'),
]

crm/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/lead/urls.py
from django.urls import path
from .views import *

app_name = 'lead'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead_list'),
    path('add_lead/', add_lead, name='add_lead'),
    path('<int:pk>/', lead_detail, name='lead_detail'),
    path('<int:pk>/delete/', leads_delete, name='lead_delete'),
    path('<int:pk>/edit/', leads_edit, name='leads_edit'),
    path('<int:pk>/convert/', convert_to_client, name='convert_to_client'),
    path('<int:pk>/add-comment', add_comment, name='add_comment'),
]

crm/team/urls.py
from django.urls import path

from .views import *

app_name='team'

urlpatterns = [
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/edit/', edit_team, name='edit_team'),
    path('team-list/', teams_list, name='teams_list'),
    path('<int:pk>/activate/', team_activate, name='activate_team'),
    
]

crm/user/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import signup, my_account

app_name = 'user'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('myaccount/', my_account, name='my_account'),
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

crm/core/models.py
from django.db import models

# Create your models here.

crm/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request,'core/about.html')

crm/core/templates/core/partials/footer.html
{% load static %}
<footer class="py-8 text-center bg-sky-200">
  <div class="container mx-auto px-4 py-6">
      
      <nav class="flex flex-wrap justify-center">
          <a href="/" class="px-4 py-2 hover:text-gray-400">Home</a>
          <a href="{% url 'core:about' %}" class="px-4 py-2 hover:text-gray-400">About Us</a>
          <a href="#" class="px-4 py-2 hover:text-gray-400">Services</a>
          <a href="#" class="px-4 py-2 hover:text-gray-400">Blog</a>
          <a href="#" class="px-4 py-2 hover:text-gray-400">Contact Us</a>
      </nav>
  </div>

  <p class="text-xs text-gray-700 pt-4">© 2023 Pravin Kamble. All rights reserved.</p>
</footer>

crm/core/templates/core/partials/nav.html
<nav class="py-6 px-6 flex justify-between bg-gray-800">
    <a href="/" class="text-white font-bold text-2xl tracking-wide">CRM</a>

    <div class="space-x-4">
        {% if request.user.is_authenticated %}
            {% if team %}
                <a href="{% url 'team:detail' active_team.id %}" class="text-white">{{ active_team.name }}</a>
            {% endif %}
            <a href="{% url 'dashboard:dashboard' %}" class="py-2 px-4 bg-teal-600 rounded-lg text-white font-medium hover:bg-teal-700 transition duration-300">Dashboard</a>
            <a href="{% url 'client:client_list' %}" class="py-2 px-4 bg-teal-600 rounded-lg text-white font-medium hover:bg-teal-700 transition duration-300">Clients</a>
            <a href="{% url 'lead:lead_list' %}" class="py-2 px-4 bg-teal-600 rounded-lg text-white font-medium hover:bg-teal-700 transition duration-300">Leads</a>
            <a href="{% url 'user:my_account' %}" class="py-2 px-4 bg-pink-600 rounded-lg text-white font-medium hover:bg-pink-700 transition duration-300">My Account</a>
            
        {% else %}
            <a href="{% url 'user:login' %}" class="py-2 px-4 bg-teal-500 rounded-lg text-white font-medium hover:bg-teal-600 transition duration-300">Login</a>
            <a href="{% url 'user:signup' %}" class="py-2 px-4 bg-teal-300 rounded-lg text-white font-medium hover:bg-teal-400 transition duration-300">Sign up</a>
        {% endif %}
        
    </div>

</nav>