crm/client/urls.py
from django.urls import path

from .views import *

app_name = 'client'

urlpatterns = [
    path('', client_list, name='client_list'),
    path('<int:pk>/', client_detail, name='client_detail'),
    path('<int:pk>/delete/', client_delete, name='client_delete'),
    path('<int:pk>/comment-delete/', delete_comment, name='comment_delete'),
    path('<int:pk>/edit/', client_edit, name='client_edit'),
    path('<int:pk>/add-comment/', client_detail, name='add_comment'),
    path('add/', add_client, name='add_client'),
    path('export/',client_export,name='client_export'),
    
    
]

crm/crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/user/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import signup, my_account

app_name = 'user'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('myaccount/', my_account, name='my_account'),
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

crm/client/models.py
from django.db import models

from django.contrib.auth.models import User

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team,related_name='clients', on_delete=models.CASCADE)
    name  = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self) -> str:
        return self.name
    

class Comment(models.Model):
    team = models.ForeignKey(Team,related_name='client_comment', on_delete=models.CASCADE)
    lead = models.ForeignKey(Client,related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='client_comment', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.created_by.username
    

class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username
   

crm/client/forms.py
from django import forms

from .models import Client, Comment, ClientFile

class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name','email', 'description',)
        
    

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

crm/client/views.py
import csv

from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from .forms import AddClientForm, AddCommentForm
from django.contrib.auth.decorators import login_required

from .models import Client
from team.models import Team
from .models import Comment



@login_required
def client_export(request):
    clients = Client.objects.filter(created_by= request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['Clients','Description','Created at','Crreated by'])

    for client in clients:
        writer.writerow([f"{client.name}", f"{client.description}", f"{client.created_at}", f"{client.created_by}"])
    
    return response


@login_required
def client_list(request):
    clients = Client.objects.filter(created_by= request.user,)

    return render(request,'client/client_list.html',{
        'clients': clients 
    })

@login_required
def client_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    teams = Team.objects.filter(created_by=request.user)
    if teams.exists():
        team = teams.first()
    else:
        team = None

    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = team 
            comment.created_by = request.user
            comment.client = client
            comment.lead = client
            print(comment.client)
            comment.save()
            return redirect('client:client_detail', pk=pk)
    else:
        form = AddCommentForm()

    return render(request,'client/client_detail.html',{
        'client': client,
        'form': form,  # add form to template context
    })


@login_required
def client_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()
    messages.success(request, 'The lead deleted successfully!')
    return redirect('client:client_list')


@login_required
def client_edit(request,pk):
    print('client_edit view called') 
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    if request.method == 'POST':
        print('POST request received')
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()
        
        messages.success(request, 'client details updated successfully!')

        return redirect('client:client_list')
    
    else:
        print('GET request received')
        form=AddClientForm(instance=client)
    
    return render(request, 'client/client_edit.html',{
        "form":form
    })

@login_required
def add_client(request):
    teams = Team.objects.filter(created_by=request.user)
    if teams.exists():
        team = teams.first()
    else:
        team = None
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        team = Team.objects.filter(created_by=request.user)[0]

        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team=team
            client.save()

            messages.success(request, 'The client added successfully!')

            return redirect('client:client_list')
    
    else:
        form = AddClientForm()



    return render(request, 'client/add_client.html',{
        "form":form,
        "team":team
    })




@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, created_by=request.user, pk=pk)
    client_pk = comment.lead.pk
    comment.delete()
    return redirect('client:client_detail', pk=client_pk)

crm/client/templates/client/add_client.html
{% extends 'core/base.html' %}

{% block title %}Client | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-6 bg-gray-100">
        <h1 class="text-2xl font-bold mb-4">Add client</h1>
        <h1 class="py-2 px-2 font-medium text-center">Your plan: {{ team.plan.max_leads|length }}</h1>
        <h1 class="py-2 px-2 font-medium text-center">Your clients: {{ team.leads.all|length }}</h1>
        {% if team.plan.max_leads|length == 0 %}
            {% if team.plan.max_leads|length >= team.leads.all|length %}
                <form method="post" action="." class="max-w-lg mx-auto bg-white rounded-lg shadow-lg p-6">
                    {% csrf_token %}

                    <div class="mb-4">
                        <label for="name" class="block text-gray-700 font-bold mb-2">Name</label>
                        {{ form.name }}
                    </div>

                    <div class="mb-4">
                        <label for="email" class="block text-gray-700 font-bold mb-2">Email</label>
                        {{ form.email }}
                    </div>

                    <div class="mb-4">
                        <label for="phone" class="block text-gray-700 font-bold mb-2">Description</label>
                        {{ form.description }}
                    </div>

                
                    <div class="flex justify-center">
                        <button class="bg-teal-500 hover:bg-teal-600 text-white font-bold py-2 px-4 rounded">
                            Submit
                        </button>
                    </div>
                </form>
            {% else %}
                <p>Oops! You have reached your limit.</p>
            {% endif %}
        {% else %}
            <p>Oops! You have reached your limit.</p>
        {% endif %}
    </div>
{% endblock %}

crm/client/templates/client/client_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }} | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-2xl font-bold">{{ client.name }}</h1>

        {% if client.description %}
            <p class="font-semibold text-gray-600 mb-2">Description:</p>
            <p class="mb-6">{{ client.description }}</p>
        {% endif %}

        <div class="flex flex-col md:flex-row">
            <div class="md:w-1/3">
                <p class="font-semibold text-gray-600 mb-2">Name:</p>
                <p class="mb-6">{{ client.name }}</p>
            </div>
            <div class="md:w-1/3">
                <p class="font-semibold text-gray-600 mb-2">Email</p>
                <p class="mb-6">{{ client.email }}</p>
            </div>
            <div class="md:w-1/3">
                <p class="font-semibold text-gray-600 mb-2">Created by:</p>
                <p class="mb-6">{{ client.created_by }}</p>
            </div>
        </div>

        <div class="flex flex-col md:flex-row">
            <div class="md:w-1/2">
                <p class="font-semibold text-gray-600 mb-2">Created at:</p>
                <p class="mb-6">{{ client.created_at|date:"d-M-Y H:i" }}</p>
            </div>
            <div class="md:w-1/2">
                <p class="font-semibold text-gray-600 mb-2">Modified at:</p>
                <p class="mb-6">{{ client.modified_at|date:"d-M-Y H:i" }}</p>
            </div>
        </div>
        <hr class="my-4">
        <a class="py-2 px-6 bg-red-800  hover:underline hover:text-white rounded-xl" href="{% url 'client:client_delete' client.id %}">Delete</a>
        <a class="py-2 px-6 bg-teal-800  hover:underline hover:text-white rounded-xl" href="{% url 'client:client_edit' client.id %}">Edit</a>
        <hr class="my-4">
        <div class="bg-gray-100 rounded-lg shadow-lg p-6">
            <h2 class="text-lg font-semibold mb-4">Comments</h2>
            {% for comment in client.comments.all %}
                <div class="bg-white rounded-lg shadow-md p-4 mb-4">
                    <div class="flex items-center mb-2">
                    <img src="{{ comment.created_by.profile.image.url }}" alt="{{ comment.created_by.username }}" class="w-8 h-8 rounded-full mr-2">
                    <p class="text-sm font-medium">{{ comment.created_by.username }}</p>
                    <p class="text-gray-500 text-xs ml-auto">Posted {{ comment.created_at|timesince }} ago</p>
                    </div>
                    <p class="text-gray-700">{{ comment.content }}</p>
                    {% if comment.created_by == request.user %}
                        <div class="mt-2 flex justify-end">
                            <a href="#" class="text-blue-500 hover:underline mr-2">Edit</a>
                            <form action="#" method="post">
                            {% csrf_token %}
                            <a href="{% url 'client:comment_delete' comment.id %}" class="text-red-500 hover:underline">Delete</a>
                            </form>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            {% if user.is_authenticated %}
              <form action="{% url 'client:add_comment' client.id %}" method="post">
                {% csrf_token %}
                <textarea name="content" class="bg-gray-200 rounded-lg w-full p-2 mb-2" rows="3" placeholder="Add a comment..."></textarea>
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">Post Comment</button>
              </form>
            {% else %}
              <p class="text-sm mt-4"><a href="{% url 'user:login' %}" class="text-blue-500 hover:underline">Log in</a> to leave a comment.</p>
            {% endif %}
            <hr class="mt-4 mb-4">
            <h2 class="mb-6 text-xl">Files</h2>

            <div class="space-y-4">
                {% for file in client.files.all %}
                    <div class="bg-gray-100 p-6 rounded-xl">
                        <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
                        
                        <a href="{{ file.file.url }}">Download</a>
                    </div>
                {% endfor %}
            </div>
    
            <form method="post" action="#" enctype="multipart/form-data">
                {% csrf_token %}
    
                {{ fileform.as_p }}
    
                <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Submit</button>
            </form>
    
         
    
        <hr class="my-4"> 

        <a href="{% url 'client:client_list' %}" class="text-teal-800 hover:underline inline-flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 fill-current" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10.707,16.707 C10.52,16.894 10.265,17 10,17 C9.735,17 9.48,16.894 9.293,16.707 L4.293,11.707 C3.902,11.316 3.902,10.684 4.293,10.293 L9.293,5.293 C9.684,4.902 10.316,4.902 10.707,5.293 C11.098,5.684 11.098,6.316 10.707,6.707 L7.414,10 L16,10 C16.552,10 17,10.448 17,11 C17,11.552 16.552,12 16,12 L7.414,12 L10.707,15.293 C11.098,15.684 11.098,16.316 10.707,16.707 Z"/>
            </svg>
            Back to clients
        </a>
          
    </div>
{% endblock %}

crm/client/templates/client/client_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit-client | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-6 bg-gray-100">
        <h1 class="text-2xl font-bold mb-4">Edit client</h1>

        <form method="post" action="." class="max-w-lg mx-auto bg-white rounded-lg shadow-lg p-6">
            {% csrf_token %}

            <div class="mb-4">
                <label for="name" class="block text-gray-700 font-bold mb-2">Name</label>
                {{ form.name }}
            </div>

            <div class="mb-4">
                <label for="email" class="block text-gray-700 font-bold mb-2">Email</label>
                {{ form.email }}
            </div>

            <div class="mb-4">
                <label for="phone" class="block text-gray-700 font-bold mb-2">Description</label>
                {{ form.description }}
            </div>

        

            <div class="flex justify-center">
                <button class="bg-teal-500 hover:bg-teal-600 text-white font-bold py-2 px-4 rounded">
                    Submit
                </button>
            </div>
        </form>
    </div>
{% endblock %}

crm/client/templates/client/client_list.html
{% extends 'core/base.html' %}

{% block title %}Clients | {{ block.super }}{% endblock %}

{% block content %}
    <div class="py-6 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <h1 class="text-3xl font-bold mb-4"></h1>
        <a href="{% url 'client:add_client' %}" class="inline-block py-3 px-6 bg-teal-600 rounded-lg text-white hover:bg-teal-700 transition-colors duration-200">Add client</a>
        {% if clients %}
            <a href="{% url 'client:client_export' %}" class="inline-block py-3 px-6 bg-teal-600 rounded-lg text-white hover:underline">Export</a>
        {% endif %}
        {% if clients %}
            <div class="mt-4 grid grid-cols-3 gap-4">
                {% for client in clients %}
                    <div class="bg-white rounded-lg overflow-hidden shadow-md">
                        <div class="px-6 py-4">
                            <div class="font-bold text-xl mb-2">
                                <a href="{% url 'client:client_detail' client.id %}" class="hover:underline">{{ client.name }}</a>
                            </div>
                            <p class="text-gray-700 text-base">{{ client.description }}</p>
                        </div>
                        <div class="px-6 py-4">
                            <p class="text-gray-700 text-base">{{ client.email }}</p>
                            <p class="text-gray-700 text-base">{{ client.created_on|date:'F j, Y' }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="mt-6 px-4">There are no clients yet...</p>
        {% endif%}
    </div>
{% endblock %}